services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.11.3
    environment:
      - MLFLOW_SERVER_ALLOWED_HOSTS=mlflow,mlflow:5001,localhost,127.0.0.1,88.96.55.189,88.96.55.189:5001
    command: >
      mlflow server
      --host 0.0.0.0 --port 5001
      --backend-store-uri sqlite:////mlflow/mlflow.db
      --artifacts-destination /mlflow/artifacts
      --serve-artifacts
    ports:
      - "5001:5001"
    volumes:
      - mlflow_data:/mlflow

  train:
    build:
      context: .
      dockerfile: docker/Dockerfile.train
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5001
    depends_on:
      - mlflow
    volumes:
      - models_data:/app/models
      - shared_data:/app/data/plots
    profiles:
      - train

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - models_data:/app/models:ro
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request;urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 5s
      timeout: 5s
      retries: 10

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    command: streamlit run frontend/app.py --server.port=8501
    environment:
      API_URL: http://api:8000
    ports:
      - "8501:8501"
    volumes:
      - shared_data:/app/data/plots:ro
    depends_on:
      api:
        condition: service_healthy

volumes:
  mlflow_data:
  models_data:
  shared_data:
